export { default as Carousell } from './carousell/carousell'
export { default as Header } from './header/header'
export { default as Section1 } from './section1/index'
export { default as Section2 } from './section2/index'
export { default as Section3 } from './section3/index'
export { default as Section4 } from './section4/index'
export { default as Section5 } from './section5/index'
export { default as Section6 } from './section6/index'
export { default as Section7 } from './section7/index'
export { default as Section8 } from './section8/index'
export {default as Footer} from './footer/footer'
